### ISSUE TITLE
Is there a way for us to bundle binaryen.js with this?

### ISSUE THREAD

**Issue by phated** [grain-lang/libbinaryen#18]
Since this is providing the bare libbinaryen, it'd be cool to also provide binaryen.js from this package.

cc @hhugo - is this possible somehow?

**Comment by hhugo** [comment]
I'm not sure to understand what you're asking for

**Comment by phated** [comment]
Currently, in [binaryen.ml](https://github.com/grain-lang/binaryen.ml/blob/master/js/dune) we use `(javascript_files binaryen.js postlude.js)` to include the JS version of binaryen. But we vendor it and include it with:
```
(rule
 (target binaryen.js)
 (action
  (copy ../vendor/js/index.es5.js binaryen.js)))
```

I was wondering if we could specify the javascript file for this library and remove the vendor logic from the bindings. Sorry if I don't have the right vocabulary to explain what I'd like to achieve 🙊

**Comment by phated** [comment]
Wondering if I should just close this out.

@hhugo What I was hoping we could do this:

```diff
 (library
  (name libbinaryen_c)
  (public_name libbinaryen.c)
  (foreign_archives binaryen)
  (c_library_flags :standard -lstdc++ -lpthread)
  (install_c_headers binaryen-c))
+ (javascript_files binaryen.js)
```

And then in `binaryen.js`, we could do:
```js
//Provides: Binaryen
var Binaryen = {}

//...And then all of the binaryen code below this that attaches to the Binaryen object
```

My understanding is that the `//Provides` will not be available to any code using this as a library, is that correct?

**Comment by hhugo** [comment]
I'm afraid I still don't quite understand the issue. 

Are you saying that the following doesn't work at the moment ? 
```
 (library
  (name libbinaryen_c)
  (public_name libbinaryen.c)
  (foreign_archives binaryen)
  (c_library_flags :standard -lstdc++ -lpthread)
  (install_c_headers binaryen-c)
 (javascript_files binaryen.js)
)
```

> My understanding is that the //Provides will not be available to any code using this as a library, is that correct?

I don't understand what you mean.
`(javascript_files binaryen.js)` means that the file will be given to js_of_ocaml whenever libbinaryen_c is used/depended on.
If you write a lib A that depend on libbinaryen_c and write jsoo stubs for A that require `Binaryen`, it should just work.

**Comment by phated** [comment]
I didn't know that would work! I'll try it out.
