### ISSUE TITLE
Can not use libbinaryen as dep

### ISSUE THREAD

**Issue by vincentdchan** [grain-lang/libbinaryen#19]
I wrote a DSL implementation in [my repo](https://github.com/vincentdchan/ocaml-binaryen-dsl).

But I want to use libbinaryen ad dependency, but it seems that it's not on the opam repo:

```
➜  ocaml-binaryen-dsl git:(master) opam install libbinaryen
[ERROR] No package named libbinaryen found.
```

**Comment by phated** [comment]
Hey @vincentdchan - cool project!

I don't have much experience with opam, but this project was merged into the opam-repository repo 11 days ago (in https://github.com/ocaml/opam-repository/pull/19980). Maybe you need to update your opam-repository sources or something.

Also note that the opam-repository-mingw fork disabled our package on windows. We have some issues open to understand why and try to fix it at https://github.com/fdopen/opam-repository-mingw/issues/101 and https://github.com/fdopen/opam-repository-mingw/pull/102

Hope that helps.

**Comment by vincentdchan** [comment]
Thank you very much. I have installed `libbinaryen` successfully after `opam update`. I will try to publish my package to opam later.

Thanks for telling the issue of mingw. It seems that it's not important for me.

Again, thanks for creating this repo. It's helpful.
